services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservice-network

  rabbitmq:
    image: rabbitmq:3-management 
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
    - microservice-network


  trainms:
    image: ahnaftahmid04/train:latest 
    container_name: train
    ports:
      - 8082:8082
    depends_on:
      - zipkin
      - rabbitmq 
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  userms:
    image: ahnaftahmid04/users:latest 
    container_name: user
    ports:
      - 8081:8081
    depends_on:
      - zipkin
      - rabbitmq 
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    
  bookingms:
    image: ahnaftahmid04/booking:latest 
    container_name: booking
    ports:
      - 8083:8083
    depends_on:
      - zipkin
      - rabbitmq
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  paymentms:
    image: ahnaftahmid04/payment:latest 
    container_name: payment
    ports:
      - 8084:8084
    depends_on:
      - zipkin
      - rabbitmq 
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  client:
    image: raihanrsd02/my-react-app:latest
    container_name: client
    ports:
      - 3000:3000
    depends_on:
      - userms
      - trainms
      - bookingms
      - paymentms
    networks:
      - microservice-network


networks:
  microservice-network:
    driver: bridge