apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80          # The port that the service listens on
      targetPort: 80    # The port on the pod where pgAdmin is running
  type: LoadBalancer     # Service type is LoadBalancer
