
name: Build and Test bookingms

on:
  push:
    branches:
      - "main"
    paths:
      - 'bookingms/**'
  pull_request:
    branches:
      - "main"
    paths:
      - 'bookingms/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Build and test bookingms
    - name: Build and Test bookingms
      run: |
        cd bookingms
        mvn -B package --file pom.xml
