name: Build and Test paymentms

on:
  push:
    branches:
      - "main"
    paths:
      - 'paymentms/**'
  pull_request:
    branches:
      - "main"
    paths:
      - 'paymentms/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Build and test paymentms
    - name: Build and Test paymentms
      run: |
        cd paymentms
        mvn -B package --file pom.xml
